### ISSUE TITLE
Not receiving message

### ISSUE THREAD

**Issue by davidsims9t** [plivo/plivo-examples-node#10]
I wrote a very basic test to see if I could receive SMS messages and it doesn't look like it's hitting my server. I've tested the script and thru my web browser and it works perfectly. Also it's not the message end point settings, because I've doubled check that too.

var express = require('express');
var app = express();

app.all('/receive_sms/', function(request, response) {
console.log(request.param("From"));
});

app.listen();

Any ideas on why this wouldn't work?

**Comment by cachrisman** [comment]
I checked you account; your Plivo number is missing an application. You have to assign a Plivo application to your Plivo number. 

Plivo Number --> Plivo Application --> AnswerURL --> your server URL

**Comment by davidsims9t** [comment]
Ah ok, that makes sense. Thank you @cachrisman !

**Comment by davidsims9t** [comment]
@cachrisman I'm still not receiving the number after setting the answer URL. It doesn't appear to be hitting the answer URL at all. Any ideas?

**Comment by Ramya-Raghu** [comment]
Could you try setting the message URL instead of answer URL in your Plivo
Application?

On Tue, Nov 10, 2015 at 12:04 PM, David Sims <notifications@github.com>
wrote:

> @cachrisman <https://github.com/cachrisman> I'm still not receiving the
> number after setting the answer URL. It doesn't appear to be hitting the
> answer URL at all. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plivo/plivo-examples-node/issues/10#issuecomment-155318476>
> .
>



-- 
*RAMYA* | PRESALES ENGINEER
Plivo, Inc. 340 Pine St, San Francisco - 94104, USA
Web: www.plivo.com | Twitter: @plivo <https://twitter.com/plivo>

**Comment by davidsims9t** [comment]
The message URL was set when I was trying it out. I removed the answer URL now, but it's still not working.

**Comment by cachrisman** [comment]
Couple things:

- Your Plivo number did not have an application associated with it. I manually associated the only app in your account with your plivo number:

![screen shot 2015-11-10 at 11 09 00 am 2](https://cloud.githubusercontent.com/assets/6521666/11073306/e0c28772-879e-11e5-8d68-bd5118826fe7.png)

You can access this screen from https://manage.plivo.com/number/ . Is this something you had already done?

- I sent a couple of text messages to your number and I can see that Plivo is correctly doing an HTTP GET to the message URL set in your application.
- I obviously don't have access to your server, so I don't know if the HTTP GET is executing the `console.log` you are looking for, but the response Plivo sees (and that I see when I do it manually) is
![screen shot 2015-11-10 at 11 24 21 am](https://cloud.githubusercontent.com/assets/6521666/11073320/ef723aa6-879e-11e5-8569-c4bca93771ff.png)

- lastly, looking at your code from the first message, `console.log(request.param("From"));`, `request.param` is depreciated in Express version 4 (see http://expressjs.com/api.html#req.param for details). On our [getting started pages on receiving an sms](https://www.plivo.com/docs/getting-started/receive-an-sms/), we use `request.body.From` (for POSTs, plus you need to include the bodyparser middleware) and `request.query.From` (for GETs).  `request.param` should still work but it'd probably be better to use `request.query.From`.

I suspect the actual cause is not associating your application with your Plivo number, but I hope the rest of my comments are helpful as well. Let us know if you get it working!
